# Generated by Django 4.2.3 on 2023-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_customer_email_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
