# Generated by Django 4.2.3 on 2023-08-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_category_customer_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="subcategory", name="category",),
        migrations.RenameField(
            model_name="shippingaddress", old_name="Country", new_name="country",
        ),
        migrations.RemoveField(model_name="customer", name="phone_number",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="SubCategory",),
    ]
