# Generated by Django 4.2.3 on 2023-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
