# Generated by Django 4.2.3 on 2023-08-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_product_category_alter_product_subcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="vintedo_append", new_name="vinted_append",
        ),
    ]
