# Generated by Django 4.2.3 on 2023-08-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_rename_vintedo_append_product_vinted_append"),
    ]

    operations = [
        migrations.RemoveField(model_name="subcategory", name="category",),
    ]
