# Generated by Django 4.2.3 on 2023-08-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_product_category_alter_product_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="ebay_append",),
        migrations.RemoveField(model_name="product", name="vinted_append",),
    ]
