# Generated by Django 4.2.3 on 2023-09-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_remove_product_ebay_append_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="allegro_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="allegro_id",
            field=models.IntegerField(null=True),
        ),
    ]
