# Generated by Django 4.2.3 on 2023-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_product_allegro_append_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="allegro_append",),
        migrations.RemoveField(model_name="product", name="olx_append",),
        migrations.AddField(
            model_name="product",
            name="allegro",
            field=models.CharField(default="not added", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="allegro_action",
            field=models.CharField(
                choices=[
                    ("change", "Change"),
                    ("add", "Add"),
                    ("delete", "Delete"),
                    ("no_action", "No Action"),
                ],
                default="no_action",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="olx",
            field=models.CharField(default="not added", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="olx_action",
            field=models.CharField(
                choices=[
                    ("change", "Change"),
                    ("add", "Add"),
                    ("delete", "Delete"),
                    ("no_action", "No Action"),
                ],
                default="no_action",
                max_length=10,
            ),
        ),
    ]
