# Generated by Django 4.2.3 on 2023-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_remove_product_allegro_append_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="allegro",),
        migrations.AddField(
            model_name="product",
            name="allegro_id",
            field=models.CharField(default="not added", max_length=20),
        ),
    ]
