# Generated by Django 4.2.3 on 2023-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_rename_allegro_id_product_allegro_offer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(default="", max_length=1000)),
                ("refresh_token", models.CharField(default="", max_length=1000)),
                ("time_of_invalidation", models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name="product", old_name="olx", new_name="olx_offer_id",
        ),
    ]
