# Generated by Django 4.2.3 on 2023-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_tokens_rename_olx_product_olx_offer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("access_token", models.CharField(default="", max_length=1000)),
                ("refresh_token", models.CharField(default="", max_length=1000)),
                ("time_of_invalidation", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(name="Tokens",),
    ]
