# Generated by Django 4.2.3 on 2023-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_token_authorizated_alter_token_access_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token", old_name="authorizated", new_name="authorized",
        ),
    ]
