# Generated by Django 4.2.3 on 2023-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_rename_authorizated_token_authorized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="access_token",
            field=models.CharField(blank=True, default="", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="refresh_token",
            field=models.CharField(blank=True, default="", max_length=5000, null=True),
        ),
    ]
